// Generated with the `scrape_api.py` file. Please don't modify this file directly!

import { APIInformation, Rating, Length } from "./NineCirclesLevel";

const downloadedAPIInfo: {[key: string]: APIInformation} = {
    '4284013': {
        name: `Nine Circles`,
        description: `Easy`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 55400458,
        likes: 3009025,
        objectCount: 14894,
        ratingType: 'Feature' as Rating
    },
    '5310094': {
        name: `Fairydust`,
        description: `Inspired by Nine Circles by Zobros! Definitely my hardest level, enjoy! Kappa. Pass is 123456!`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 7068307,
        likes: 393469,
        objectCount: 10969,
        ratingType: 'Feature' as Rating
    },
    '6664095': {
        name: `The Realistic`,
        description: `Inspire Nine Circles. pass and video is on my youtube channel. error fix and update`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 924446,
        likes: 92131,
        objectCount: 18783,
        ratingType: 'Feature' as Rating
    },
    '6892453': {
        name: `Figures`,
        description: `I wanted to do nine circles map cause everyone is doing one. dont take it seriously`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 1695464,
        likes: 143247,
        objectCount: 7056,
        ratingType: 'Feature' as Rating
    },
    '6939821': {
        name: `Jawbreaker`,
        description: `Inspired by Zobros. Harder than nine circles? Demon or I cry`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 11586351,
        likes: 650029,
        objectCount: 10810,
        ratingType: 'Feature' as Rating
    },
    '6988264': {
        name: `Astronaut 13`,
        description: `Inspired by Nine Circles, you can call this Shadow Circles. Yeah its stupid, pass on YT vid.`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 1290346,
        likes: 100846,
        objectCount: 13819,
        ratingType: 'Feature' as Rating
    },
    '6996731': {
        name: `Headrush`,
        description: `What a Rush. Reverified by qcAlex. Reverted.`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 291422,
        likes: 33232,
        objectCount: 12528,
        ratingType: 'Feature' as Rating
    },
    '7002072': {
        name: `classic`,
        description: `Fixed some bugs.`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 364452,
        likes: 29889,
        objectCount: 9148,
        ratingType: 'Feature' as Rating
    },
    '7018102': {
        name: `Silhouette`,
        description: `My hardest level yet. Inspired by Nine Circles. Good Luck.`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 443311,
        likes: 39999,
        objectCount: 11303,
        ratingType: 'Feature' as Rating
    },
    '7054561': {
        name: `Poltergeist`,
        description: `Poltergeist by Andromeda`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 6381590,
        likes: 331649,
        objectCount: 14871,
        ratingType: 'Feature' as Rating
    },
    '7116121': {
        name: `Problematic`,
        description: `Inspired by Nine Circles and Fairydust. A fun DEMON stage! Pass on my channel!`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 18800450,
        likes: 1029601,
        objectCount: 8462,
        ratingType: 'Feature' as Rating
    },
    '7203561': {
        name: `Classical`,
        description: `Robtop, thank you so much for the rating!`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 287351,
        likes: 21868,
        objectCount: 11710,
        ratingType: 'Feature' as Rating
    },
    '7294616': {
        name: `Classical`,
        description: `Fixed some bugs. Video on my YT channel  GmD RayOriens`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 126515,
        likes: 5619,
        objectCount: 14688,
        ratingType: 'Feature' as Rating
    },
    '7614092': {
        name: `Evil `,
        description: `New update :D Added some deco (like always) And Secret Way removed xd. `,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 217694,
        likes: 26061,
        objectCount: 20747,
        ratingType: 'Feature' as Rating
    },
    '7705437': {
        name: `Fear Me`,
        description: `Bluish crispy Nine Circles based map. Password is on my youtube channel (2.0 update ver.3)`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 1494373,
        likes: 139048,
        objectCount: 14341,
        ratingType: 'Feature' as Rating
    },
    '8147005': {
        name: `Down Bass`,
        description: `Another generic NC level`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 2770218,
        likes: 127405,
        objectCount: 16604,
        ratingType: 'Feature' as Rating
    },
    '8418966': {
        name: `fractured circles`,
        description: `i have a version with no bugs but it wont update so sorry its ok if you hate me`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 838835,
        likes: 81853,
        objectCount: 9631,
        ratingType: 'Feature' as Rating
    },
    '8723596': {
        name: `Sine Wavs`,
        description: `2022 Update (Pls i'm 100% sure it's way better than before)`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 583983,
        likes: 39497,
        objectCount: 14337,
        ratingType: 'Feature' as Rating
    },
    '9603387': {
        name: `sharp`,
        description: `Very hard player color Nine Circles styled level, good luck :D // UPDATE: buff + coins`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 298770,
        likes: 19750,
        objectCount: 13769,
        ratingType: 'Feature' as Rating
    },
    '9608518': {
        name: `Butterfly Effect`,
        description: `I started building this level when "The Realistic" was released, pass is song ID, Thanks RobTop`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 804371,
        likes: 70423,
        objectCount: 17671,
        ratingType: 'Feature' as Rating
    },
    '9682304': {
        name: `Golden Hope`,
        description: `bugfix :)`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 426884,
        likes: 34516,
        objectCount: 17667,
        ratingType: 'Feature' as Rating
    },
    '9700312': {
        name: `Crimson Clutter`,
        description: `Oh no, another nine circles level. A dark red one infact. Credits for the name goes to Lumpy. Demon?`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 1187693,
        likes: 75823,
        objectCount: 10828,
        ratingType: 'Feature' as Rating
    },
    '9864147': {
        name: `Space Circles`,
        description: `Updated Version - Video & Password on My YouTube channel:   Geometry Dash Suomi`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 1167695,
        likes: 94410,
        objectCount: 9920,
        ratingType: 'Feature' as Rating
    },
    '10197026': {
        name: `Paracosm Circles`,
        description: `Have Fun! password on Leksitoo channel!`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Medium' as Length,
        downloads: 5694004,
        likes: 274908,
        objectCount: 15233,
        ratingType: 'Feature' as Rating
    },
    '10312917': {
        name: `Sharp Minor`,
        description: `Sharp minor  aka Golden circles... Collab with ASonicMen... Demon?`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 455908,
        likes: 37037,
        objectCount: 17428,
        ratingType: 'Feature' as Rating
    },
    '10789222': {
        name: `Catastrophic`,
        description: `The debt has been repaid. Bugs fixed, password enabled and coins added. I'm sorry that it took this long. Thank you for believing.`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 215322,
        likes: 14955,
        objectCount: 18889,
        ratingType: 'Feature' as Rating
    },
    '10807587': {
        name: `Sweet Dreams`,
        description: `Wow. GHS beat it.. whos next..now? >:) Free copy. `,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 223802,
        likes: 18534,
        objectCount: 9977,
        ratingType: 'Feature' as Rating
    },
    '10890011': {
        name: `Windy Circles`,
        description: `Inspired by Nine Circles and JawBreaker. Difficulty Up and Reupload.`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 628507,
        likes: 34838,
        objectCount: 10925,
        ratingType: 'Feature' as Rating
    },
    '10972106': {
        name: `Solar Circles`,
        description: `ITS FINALLY HERE !!`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 310678,
        likes: 34972,
        objectCount: 12944,
        ratingType: 'Feature' as Rating
    },
    '11346695': {
        name: `Planet Circles`,
        description: `The Final Chapter. `,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 151154,
        likes: 11023,
        objectCount: 16440,
        ratingType: 'Feature' as Rating
    },
    '11588490': {
        name: `Ultra Paracosm`,
        description: `El primer "Ultra Circles", mi primer Demon con estrellas y un clasico de GD | v19. LDM en Wave y arreglos menores`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 13155970,
        likes: 827308,
        objectCount: 21736,
        ratingType: 'Feature' as Rating
    },
    '12070173': {
        name: `Frozen Jawbreaker`,
        description: `Redeco and better gameplay, deco by Clover LDM = Old Version`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 48909,
        likes: 3601,
        objectCount: 28826,
        ratingType: 'Feature' as Rating
    },
    '12073525': {
        name: `Ultra Fairydust`,
        description: `Mucho mas estable que la version anterior, dificultad balanceada, 70% arreglado (Borren el nivel y vuelvanlo a descargar para actualizarlo)`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 717686,
        likes: 65450,
        objectCount: 24415,
        ratingType: 'Feature' as Rating
    },
    '12423506': {
        name: `Crying Souls`,
        description: `My first 2.0 level! and it ain't easy! plz rate demon! (verifyed by Geomania)`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 437731,
        likes: 32677,
        objectCount: 25948,
        ratingType: 'Feature' as Rating
    },
    '12568393': {
        name: `Ultra Circles`,
        description: `Visita mi canal Rulasjunior25! -26666 objetos- Ultima "2016 Update", esta vez del Ultra mas dificil >:). Disfruten y gracias totales p=24525`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 712144,
        likes: 44761,
        objectCount: 26657,
        ratingType: 'Feature' as Rating
    },
    '13037894': {
        name: `infinite circles `,
        description: `8)`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 8019583,
        likes: 464112,
        objectCount: 10648,
        ratingType: 'Feature' as Rating
    },
    '13114485': {
        name: `infinite circles v2`,
        description: `Harder version of Infinite Circles by Startor.`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 483001,
        likes: 25527,
        objectCount: 17998,
        ratingType: 'Feature' as Rating
    },
    '13501597': {
        name: `The RealistiK`,
        description: `Demon. My 2nd 2.01 level. Enjoy :)`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 106428,
        likes: 7613,
        objectCount: 19538,
        ratingType: 'Feature' as Rating
    },
    '13530154': {
        name: `Infernity`,
        description: `41800 Objects. GL HF to all of you! Thanks to illuminati6, Frotzn and Xaro! Low Detail activator in the first cube!`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 206663,
        likes: 22312,
        objectCount: 41797,
        ratingType: 'Feature' as Rating
    },
    '13575944': {
        name: `SuperNova`,
        description: ``,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 242505,
        likes: 15456,
        objectCount: 16149,
        ratingType: 'Feature' as Rating
    },
    '13641664': {
        name: `Antique Circles`,
        description: `Some tell the tales about the old circles, now it's time for you to tell yours`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 190118,
        likes: 17931,
        objectCount: 17681,
        ratingType: 'Feature' as Rating
    },
    '13703326': {
        name: `Nine Circles XII`,
        description: `Replaced the song since Xtrullor doesn't make songs for GD anymore.`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 3556737,
        likes: 139722,
        objectCount: 19405,
        ratingType: 'Feature' as Rating
    },
    '13704546': {
        name: `Ultimate Circles`,
        description: `Updated version! Video & Password on my YouTube channel:  Geometry Dash Suomi`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 3218001,
        likes: 231704,
        objectCount: 17095,
        ratingType: 'Feature' as Rating
    },
    '14000484': {
        name: `Retro Circles`,
        description: `"Nine Circles" retro. Mi primera joya en mi carrera. Practica bien el nivel y buena suerte.`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 9344180,
        likes: 620019,
        objectCount: 44822,
        ratingType: 'Feature' as Rating
    },
    '14019412': {
        name: `Invisible Light`,
        description: ` `,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 1122859,
        likes: 97560,
        objectCount: 20696,
        ratingType: 'Feature' as Rating
    },
    '14030404': {
        name: `Circulatum`,
        description: `Collab with Xaverious .. Circulatum II Comming soon !! Update Effect at drop and low detail`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 97548,
        likes: 13422,
        objectCount: 29908,
        ratingType: 'Feature' as Rating
    },
    '14309230': {
        name: `AnotherCircles`,
        description: `That moment when you realize... A Nine Circles level is now an effect level :O  Verified by Xiodazer!`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 295992,
        likes: 34926,
        objectCount: 15275,
        ratingType: 'Feature' as Rating
    },
    '14321727': {
        name: `Quasar`,
        description: `Oh yeah! Here it is- a Nine Circles level, Allan style! Ez/medium demon, perhaps? Video and pass on my Youtube channel. GG Quasar! ;3; )/`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 211553,
        likes: 22264,
        objectCount: 30455,
        ratingType: 'Feature' as Rating
    },
    '14960319': {
        name: `Paracosm XII`,
        description: `Description [Optional]`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 162662,
        likes: 11484,
        objectCount: 17496,
        ratingType: 'Feature' as Rating
    },
    '17796070': {
        name: `Blacklight`,
        description: `No hate for making an NC? 8) verified by Maudanik. Over 5k triggers, my masterpiece. Pass is 2255. Only the beginning is hard`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 160051,
        likes: 15485,
        objectCount: 44525,
        ratingType: 'Feature' as Rating
    },
    '20785077': {
        name: `Astronaut 13`,
        description: `Turquoise Circles! Collab with Complexx, who made Classic! Check out Windy Monster too!`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 43556,
        likes: 3397,
        objectCount: 12040,
        ratingType: 'Feature' as Rating
    },
    '21306256': {
        name: `Future Circles`,
        description: `Inspired by Nine Circles       -Thanks to everyone for playing this:) especially Koreaqwer and Skitten-`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 549865,
        likes: 36956,
        objectCount: 29057,
        ratingType: 'Feature' as Rating
    },
    '26245696': {
        name: `Trump Circles`,
        description: `Collab By me, Axxorz, Moufi, Gibbon, Darwin and TiTi. Final pixel art by TiTi too. Well Okay... v2: LDM added`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 4478212,
        likes: 275585,
        objectCount: 46408,
        ratingType: 'Feature' as Rating
    },
    '26441161': {
        name: `Flat Major`,
        description: `Fixed some bugs lmfao, and changed somethings`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Medium' as Length,
        downloads: 844527,
        likes: 50532,
        objectCount: 28839,
        ratingType: 'Feature' as Rating
    },
    '26681070': {
        name: `Sonic Wave`,
        description: `Mythical Demon by Cyclic! Video on my YouTube.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 25446843,
        likes: 830076,
        objectCount: 23157,
        ratingType: 'Feature' as Rating
    },
    '30380566': {
        name: `Bausha Vortex`,
        description: `videogame level that is hard. beat only if good`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 915363,
        likes: 52159,
        objectCount: 27051,
        ratingType: 'Feature' as Rating
    },
    '33405303': {
        name: `The Secret Box`,
        description: `Nerfed Back down, so it's more "fun" now`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 762412,
        likes: 49255,
        objectCount: 27238,
        ratingType: 'Feature' as Rating
    },
    '36099108': {
        name: `pulsar`,
        description: `A collab between me and zhander. Honestly he is an amazing creator took 1575 attempts to verify`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 1178078,
        likes: 152012,
        objectCount: 67390,
        ratingType: 'Epic' as Rating
    },
    '36522386': {
        name: `Nine CircleX`,
        description: `Zobros asked me to remake and upload his last project, Nine Circles X. Collaboration between me, Rustam and Zobros. Verified by Maxis9.`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 2908850,
        likes: 128231,
        objectCount: 67851,
        ratingType: 'Epic' as Rating
    },
    '36831819': {
        name: `Power`,
        description: `The power is wonderful, but sometimes, dangerous. Old collaboration with netrin!`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 59073,
        likes: 3886,
        objectCount: 44742,
        ratingType: 'Feature' as Rating
    },
    '36886759': {
        name: `Poltergeist Reborn`,
        description: `Poltergeist Reborn made by Pennutoh and verified by me in 20654 attempts.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 250104,
        likes: 10039,
        objectCount: 27555,
        ratingType: 'Feature' as Rating
    },
    '38765979': {
        name: `Mujigae`,
        description: `Embrace it... Live it... Love it... The spectrum... Dedicated to swithi and chuck. Thanks for supporting. Bugfix #2`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 121639,
        likes: 5511,
        objectCount: 111249,
        ratingType: 'Feature' as Rating
    },
    '39495014': {
        name: `Despacito Circles`,
        description: `An amazing collab between me, Darwin, and Kips. Thanks to Luqualizer for verification! Might get rated due to the song (Ground Zero).`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 275509,
        likes: 20189,
        objectCount: 30780,
        ratingType: 'Feature' as Rating
    },
    '41409797': {
        name: `Undergound`,
        description: `Created on the 1.9 GDPS, Hard/Insane NC Demon made by me, fixed some bugs`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 45932,
        likes: 3087,
        objectCount: 30423,
        ratingType: 'Feature' as Rating
    },
    '42117203': {
        name: `Hyper Paracosm`,
        description: `Update by Joe`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 420811,
        likes: 26723,
        objectCount: 41950,
        ratingType: 'Feature' as Rating
    },
    '46249401': {
        name: `Abandoned Planet`,
        description: `Extreme NC demon started in 2.0, second half finished in 2.1 to give a more accurate description. crazy it's actully rated, thanks a lot.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 74456,
        likes: 4153,
        objectCount: 63766,
        ratingType: 'Feature' as Rating
    },
    '47853491': {
        name: `Tengu Wind`,
        description: `My first bossfight level (and yes it is also a NC level). Thanks for playing.`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 81424,
        likes: 8766,
        objectCount: 39256,
        ratingType: 'Feature' as Rating
    },
    '48435217': {
        name: `Bakuretsu`,
        description: `Modernistic with nine circle effect :D collab with RehanZ and verified by khayangan.(For Enlex cc 3)`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 36409,
        likes: 3298,
        objectCount: 66872,
        ratingType: 'Feature' as Rating
    },
    '49576382': {
        name: `Generic Wave`,
        description: `The only level in the entire game. Verified by Mullsy, collab with Enlex`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 365235,
        likes: 11676,
        objectCount: 108258,
        ratingType: 'Feature' as Rating
    },
    '49901047': {
        name: `End Line`,
        description: `My first 2.1 map! I don't wanna get featured. I just want to make maps what I want!(like this...) Password is 026000!(Fixed 144hz bug)`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 67542,
        likes: 6047,
        objectCount: 26000,
        ratingType: 'Feature' as Rating
    },
    '52919433': {
        name: `Arctic Lights`,
        description: `The hardest circles level, created by ViRuZ and Endlevel.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 438431,
        likes: 17445,
        objectCount: 44595,
        ratingType: 'Feature' as Rating
    },
    '55385816': {
        name: `Balengu Vortex`,
        description: `A remake of Bausha Vortex by Pennutoh. Made by Temp, ItsHybrid, and HJfod.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 164646,
        likes: 8088,
        objectCount: 59981,
        ratingType: 'Feature' as Rating
    },
    '57395071': {
        name: `Hue Effect`,
        description: `~ Colorful remake of my favorite NC level "Butterfly Effect" by Linco ~ | Dedicated to my Furret Gang & 1.9 nostalgists |`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 636920,
        likes: 44393,
        objectCount: 36963,
        ratingType: 'Feature' as Rating
    },
    '57410372': {
        name: `Nine Paws`,
        description: `From the old Nine Circles, Nine Paws resurfaces, the new modern NC that will surprise you all. My new MC with epic creators!! LDM ADDED!`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 262163,
        likes: 16350,
        objectCount: 108079,
        ratingType: 'Epic' as Rating
    },
    '59533451': {
        name: `Azurite`,
        description: `thwomp.mp3`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 118395,
        likes: 3854,
        objectCount: 110459,
        ratingType: 'Feature' as Rating
    },
    '60740290': {
        name: `Aquatic Auroras`,
        description: `verified by harry styles`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 234348,
        likes: 9573,
        objectCount: 92187,
        ratingType: 'Feature' as Rating
    },
    '60960827': {
        name: `Astronaut 14`,
        description: `Astronaut 13 remake. Collab with Alfian10, for "GDS CC" Verified by PrayogaGD`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 53441,
        likes: 2761,
        objectCount: 59046,
        ratingType: 'Feature' as Rating
    },
    '61132346': {
        name: `Hateful Reflection`,
        description: `Hate.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 119427,
        likes: 6794,
        objectCount: 81292,
        ratingType: 'Feature' as Rating
    },
    '61531210': {
        name: `Hyper Paradox`,
        description: `Enter the paradox of the paracosms.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 145830,
        likes: 5540,
        objectCount: 78188,
        ratingType: 'Feature' as Rating
    },
    '62133870': {
        name: `Broken Reality`,
        description: `Amazing NC Level Made by Zerenity, Verified by Me!! Remade 1.9 level (Puries Fantasy)`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 73194,
        likes: 5140,
        objectCount: 58669,
        ratingType: 'Feature' as Rating
    },
    '62592746': {
        name: `Tenth Circle`,
        description: `Gameplay: First 70% - NormDanchik; last 30% - Me. Decor - DeniPol(me). Verified - Dorami & Blitzer. Istochnik: https://youtu.be/Wl959QnD3lM`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 423065,
        likes: 19224,
        objectCount: 84422,
        ratingType: 'Epic' as Rating
    },
    '62923992': {
        name: `Sparkling Hope`,
        description: `Pink-purple NC level xdddddddd. Verified by Timo`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 77659,
        likes: 7327,
        objectCount: 69489,
        ratingType: 'Feature' as Rating
    },
    '63842337': {
        name: `Fnafbass`,
        description: `Gameplay by The181, Decoration by ThatKai, verified by me. Inside joke collab that went way too far.`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 161224,
        likes: 6717,
        objectCount: 40172,
        ratingType: 'Feature' as Rating
    },
    '64612787': {
        name: `Zacarias`,
        description: `New BrazilTeam's level that has been updated to my account. Enjoy! Verified by Mxteus`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 72157,
        likes: 7206,
        objectCount: 116551,
        ratingType: 'Feature' as Rating
    },
    '64902117': {
        name: `Meteoric Debris`,
        description: `daze`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 42225,
        likes: 2832,
        objectCount: 47608,
        ratingType: 'Feature' as Rating
    },
    '65046970': {
        name: `Apollo 13`,
        description: `Originally planned as the GDS CC entry by endlevel and me, now a solo remake of Astronaut 13 by Minesap, should be a Very Hard/Insane Demon.`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 62831,
        likes: 2725,
        objectCount: 41113,
        ratingType: 'Feature' as Rating
    },
    '68414488': {
        name: `Molten Core`,
        description: `Jeszcze Polska nie zginela, Kiedy my zyjemy. Co nam obca przemoc wziela, Szabla odbierzemy.   J E B A C     P I S`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 122016,
        likes: 5050,
        objectCount: 68866,
        ratingType: 'Feature' as Rating
    },
    '68688849': {
        name: `Sonic Wave Rebirth`,
        description: `Collab with FunnyGame, Verified by Moosh.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 1754783,
        likes: 45655,
        objectCount: 52482,
        ratingType: 'Epic' as Rating
    },
    '69685815': {
        name: `Sonic Wave Infinity`,
        description: `Legendary Demon by APTeam. Verified by Xanii. Legacy Mode can be enabled with LDM Checkbox. Legacy Concept by Viprin. Version 2.0`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 2237185,
        likes: 83521,
        objectCount: 247024,
        ratingType: 'Feature' as Rating
    },
    '69871779': {
        name: `Friday Vortex`,
        description: `And next friday night, we'll do it all again. Dedicated to Slithium, Declan, Tuggy, GrenadeofTacos, and SaRy... SONG IS ON MY YOUTUBE`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 58371,
        likes: 2307,
        objectCount: 49340,
        ratingType: 'Feature' as Rating
    },
    '72011288': {
        name: `Falling Stars`,
        description: `Verified by Perlite, dedicated to EVW and Knots. Enjoy, rate insane demon and good luck :D (Nerfdate: first drop transition is easier now)`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 43110,
        likes: 2071,
        objectCount: 91100,
        ratingType: 'Feature' as Rating
    },
    '72449577': {
        name: `In Cargill`,
        description: `Shapes from form and void. Good luck!`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 37594,
        likes: 2236,
        objectCount: 183632,
        ratingType: 'Feature' as Rating
    },
    '72810041': {
        name: `ZXCircleS`,
        description: `Coil Coil Coil`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 1575082,
        likes: 117395,
        objectCount: 35715,
        ratingType: 'Feature' as Rating
    },
    '76159410': {
        name: `Cosmic Cyclone`,
        description: `Sequel to the legendary Sonic Wave by Cyclic. Verified by DoSh7t. Made by APTeam. (v1.3)`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 285352,
        likes: 15342,
        objectCount: 211997,
        ratingType: 'Feature' as Rating
    },
    '76962930': {
        name: `Sakupen Circles`,
        description: `By Nick24, DrCuber, korewa, Muffy450, Renn241, endevvor, Mzero, NineDice, GhostVandalf. Dedicated to Cursed`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Medium' as Length,
        downloads: 4256253,
        likes: 155371,
        objectCount: 69055,
        ratingType: 'Feature' as Rating
    },
    '77132030': {
        name: `Ratio Circles`,
        description: `Made in 3 days. Happy new year everyone :)`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Medium' as Length,
        downloads: 480787,
        likes: 31986,
        objectCount: 24979,
        ratingType: 'Feature' as Rating
    },
    '78964835': {
        name: `SemiCircles`,
        description: `Any angle inscribed in a semicircle will always have a measure of 90 degrees. Made on the 1.9 GDPS!`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 55763,
        likes: 4586,
        objectCount: 32057,
        ratingType: 'Feature' as Rating
    },
    '79182381': {
        name: `flea`,
        description: `And quite a spanish one at that.`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Medium' as Length,
        downloads: 188209,
        likes: 9059,
        objectCount: 42023,
        ratingType: 'Feature' as Rating
    },
    '79489649': {
        name: `HamDuck Vortex`,
        description: ``,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 54396,
        likes: 4655,
        objectCount: 86751,
        ratingType: 'Feature' as Rating
    },
    '79862130': {
        name: `Mehdi`,
        description: `dedicated to qventiam. thank you royen for your previous verifications [1.9 GDPS nc level]`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 22358,
        likes: 1495,
        objectCount: 79048,
        ratingType: 'Feature' as Rating
    },
    '81139702': {
        name: `The Hallucination`,
        description: `Psychedelic. layout and verified by Votchi`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 238706,
        likes: 11873,
        objectCount: 159614,
        ratingType: 'Feature' as Rating
    },
    '81748963': {
        name: `Through The Aether`,
        description: `Take a journey through an alternate dimension. My latest attempt at making a NC level, let me know what you think!`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 19190,
        likes: 1240,
        objectCount: 59703,
        ratingType: 'Feature' as Rating
    },
    '84766628': {
        name: `Cat Planet`,
        description: `My only easy level, Enjoy ^,^  - C4T PL4N3T -`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 327289,
        likes: 11298,
        objectCount: 35551,
        ratingType: 'Feature' as Rating
    },
    '86565813': {
        name: `Fishbass`,
        description: `you hear about fishbass? (use ldm if using nong)`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 89656,
        likes: 4715,
        objectCount: 57331,
        ratingType: 'Feature' as Rating
    },
    '87353798': {
        name: `Carp Minor`,
        description: `im a little fishy ;3 awa m so hap am takin estroutgen and m gonna be girlfish! OMG ;3; THEY CAUGHT ME A :( whyre they bringin me 2 th piano?")`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 49910,
        likes: 2762,
        objectCount: 76448,
        ratingType: 'Feature' as Rating
    },
    '88853479': {
        name: `cerebral hemorrhage`,
        description: `Remake of a old 2018 level i made :) Started 9/20/2022 and finished 2/19/2023. Nerf date 5/13/2023`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 38675,
        likes: 1471,
        objectCount: 97163,
        ratingType: 'Feature' as Rating
    },
    '88873060': {
        name: `ACCELERATOR`,
        description: `Accelerate! Playtested by spark, Raivolt, ZachLy, and Tuuns. For Icarus CC2!`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 146488,
        likes: 7745,
        objectCount: 69851,
        ratingType: 'Epic' as Rating
    },
    '89876243': {
        name: `FIREPOWER`,
        description: `L|O_O|J Your skull as a child did not drop as hard as this map L|X_X|J L|+_+|J`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 93882,
        likes: 3899,
        objectCount: 179999,
        ratingType: 'Epic' as Rating
    },
    '90222644': {
        name: `The Mines Circles`,
        description: `The children yearn for The Mines :tm:`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 16677,
        likes: 830,
        objectCount: 73571,
        ratingType: 'Feature' as Rating
    },
    '90390075': {
        name: `Solar Flare`,
        description: `The star's name is Janet, please be nice to her.`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 168865,
        likes: 7373,
        objectCount: 68260,
        ratingType: 'Epic' as Rating
    },
    '94179418': {
        name: `Haywire`,
        description: `My first full solo level after 7+ years of using the editor. Made for IcarusCC 2. Thank you all <3`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 45266,
        likes: 3652,
        objectCount: 79982,
        ratingType: 'Epic' as Rating
    },
    '94547076': {
        name: `Psychedelic Circles`,
        description: `Don't do drugs, kid.`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 125930,
        likes: 5254,
        objectCount: 134553,
        ratingType: 'Epic' as Rating
    },
    '94563744': {
        name: `tipo B`,
        description: `for icarus CC | made in 3 moths   -->  Tipo B me lembrou slaughterhouse , UNDERGROUND , Accelerate. ~ Matheus9618`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 76721,
        likes: 7508,
        objectCount: 107186,
        ratingType: 'Feature' as Rating
    },
    '94591693': {
        name: `Ten Circles`,
        description: `For Icarus CC2 | Another NC themed level with DeniPol! Enjoy ;)`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 79062,
        likes: 5957,
        objectCount: 57481,
        ratingType: 'Feature' as Rating
    },
    '94591772': {
        name: `Nomostros Cosmos`,
        description: `Inside of the aircraft, a scientist decides to make an expirement when suddenly, it fails and gets absorbed by a black hole. His goal: find an exit. || For IcarusCC2`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 111464,
        likes: 7535,
        objectCount: 99212,
        ratingType: 'Epic' as Rating
    },
    '94595730': {
        name: `After Image`,
        description: `Nine.Circles.exe is dangerous bot that has been depriving levels from their creativity ever since 1.9. (For Icarus CC2)`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 13867,
        likes: 794,
        objectCount: 72558,
        ratingType: 'Feature' as Rating
    },
    '94599528': {
        name: `Spacetime Error`,
        description: `My entry for Icarus CC2. A small journey through space with a cybernetic essence that is conflicted by the presence of a black hole. LDM recommended for low-end devices.`,
        difficulty: 'Medium Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 78076,
        likes: 7395,
        objectCount: 62256,
        ratingType: 'Feature' as Rating
    },
    '94610370': {
        name: `Ring Trick`,
        description: `Come with me onto a journey like never before.. (For Icarus CC2)`,
        difficulty: 'Hard Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 184033,
        likes: 9773,
        objectCount: 119532,
        ratingType: 'Epic' as Rating
    },
    '94772024': {
        name: `Astrophobia`,
        description: `Made entirely on the 1.9 GDPS! Featuring Royen & Valentine. Verified by me, added coin in 2.1!`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 28804,
        likes: 1499,
        objectCount: 95657,
        ratingType: 'Feature' as Rating
    },
    '95255152': {
        name: `Bete Noire`,
        description: `Official sequel of Fear Me by CrispyDash - 08/10/23 | Hosted by Phantom7Ks - Verified by Diamond | #ThePurgatorySupremacy`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 25749,
        likes: 1396,
        objectCount: 129211,
        ratingType: 'Feature' as Rating
    },
    '95524621': {
        name: `Crackhead Circles`,
        description: `dont do drugs - verified by teraaa - bugfix update for mac`,
        difficulty: 'Extreme Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 55870,
        likes: 1941,
        objectCount: 94811,
        ratingType: 'Feature' as Rating
    },
    '99246761': {
        name: `it really circles`,
        description: `Decided to make my own nine circles level since the game doesnt have enough, hope you enjoy :3`,
        difficulty: 'Easy Demon',
        stars: 10,
        length: 'Long' as Length,
        downloads: 48685,
        likes: 2742,
        objectCount: 49370,
        ratingType: 'Feature' as Rating
    },
    '102265892': {
        name: `Sonic Wave Unlimited`,
        description: `Sonic Wave Unlimited releasing in 1 NOW! CAN YOU SURVIVE? By APTeamButAwesome and more!!!!`,
        difficulty: 'Insane Demon',
        stars: 10,
        length: 'XL' as Length,
        downloads: 136442,
        likes: 7305,
        objectCount: 148804,
        ratingType: 'Feature' as Rating
    },
    '3151283': {
        name: `Beginning of Colours`,
        description: `bug fixed (finally) pass is 697034`,
        difficulty: 'Auto',
        stars: 1,
        length: 'Long' as Length,
        downloads: 336497,
        likes: 62225,
        objectCount: 13860,
        ratingType: 'Feature' as Rating
    },
    '3472006': {
        name: `vesuve`,
        description: `It was not a good idea to go hiking on that mountain ! ... Can you SURVIVE ?? Use gray`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 40232,
        likes: 4396,
        objectCount: 14430,
        ratingType: 'Feature' as Rating
    },
    '5256745': {
        name: `new stereo madness`,
        description: `Second of Fever Remix Series ! My Entry For Etzer Contest !!  Mini jewel by MetalCruiser support him`,
        difficulty: 'Hard',
        stars: 4,
        length: 'Long' as Length,
        downloads: 153200,
        likes: 18439,
        objectCount: 20512,
        ratingType: 'Feature' as Rating
    },
    '5753157': {
        name: `Chaoz Devotion`,
        description: `chaoz devotion`,
        difficulty: 'Hard',
        stars: 5,
        length: 'Long' as Length,
        downloads: 25886,
        likes: 3547,
        objectCount: 5473,
        ratingType: 'Feature' as Rating
    },
    '6361170': {
        name: `If 9 Circles was Lv1`,
        description: `No more PASS for u guys till I see less copies, which wont be anytime soon. Please dont steal.`,
        difficulty: 'Hard',
        stars: 4,
        length: 'Long' as Length,
        downloads: 2623284,
        likes: 433367,
        objectCount: 8932,
        ratingType: 'Feature' as Rating
    },
    '6877843': {
        name: `If Fairydust was L1`,
        description: `Cool ! New update ! To download the level, you can get the password on my video on my Youtube channel : MorpheiX :)`,
        difficulty: 'Normal',
        stars: 3,
        length: 'Long' as Length,
        downloads: 1192595,
        likes: 199746,
        objectCount: 11286,
        ratingType: 'Feature' as Rating
    },
    '6977311': {
        name: `the realistik v2`,
        description: `thanks RobTop   , pass 123456`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 98311,
        likes: 9945,
        objectCount: 13517,
        ratingType: 'Feature' as Rating
    },
    '7083373': {
        name: `Nine caveS `,
        description: `2.0 coin update! This level lags now, I did what I could. Enjoy and don't forget to check out my other levels!`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 76008,
        likes: 4791,
        objectCount: 22559,
        ratingType: 'Feature' as Rating
    },
    '7203798': {
        name: `lightsaber battle`,
        description: `Check out my other levels ;)`,
        difficulty: 'Auto',
        stars: 1,
        length: 'Long' as Length,
        downloads: 272127,
        likes: 53267,
        objectCount: 9338,
        ratingType: 'Feature' as Rating
    },
    '8112546': {
        name: `Dark matter`,
        description: `Enjoy! or smash your keyboard. Rate insane.`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 44856,
        likes: 5004,
        objectCount: 8078,
        ratingType: 'Feature' as Rating
    },
    '8331090': {
        name: `classical`,
        description: `pls sub to my yt channel - geometry dash d4sh3r! became harder - demon now?..`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 103562,
        likes: 8183,
        objectCount: 10549,
        ratingType: 'Feature' as Rating
    },
    '8725630': {
        name: `Dual Extreme `,
        description: `I'm unable to fix all the bugs 'cause there are so many things who can cause you to die, I can try but I'm afraid to cause new ones instead`,
        difficulty: 'Auto',
        stars: 1,
        length: 'Long' as Length,
        downloads: 201191,
        likes: 24061,
        objectCount: 15298,
        ratingType: 'Feature' as Rating
    },
    '8883107': {
        name: `Autosonic`,
        description: `Fixed 28% bug for everyone and a few other bugs.`,
        difficulty: 'Auto',
        stars: 1,
        length: 'Medium' as Length,
        downloads: 597914,
        likes: 70162,
        objectCount: 8997,
        ratingType: 'Feature' as Rating
    },
    '9315108': {
        name: `For The Taking`,
        description: `Final Update!! Special thanks to ItzCheesy and Chillius for help.`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 96362,
        likes: 9501,
        objectCount: 10466,
        ratingType: 'Feature' as Rating
    },
    '9803621': {
        name: `Rising Circles`,
        description: `V2 - fixed a lot of bugs. Thx 4 feature, pass 10782. Also try my other levels!`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 239535,
        likes: 35856,
        objectCount: 10782,
        ratingType: 'Feature' as Rating
    },
    '10125163': {
        name: `dorabaebasic10`,
        description: `Inspired Nine Circles.  DORABAE-BASIC10. `,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 14041437,
        likes: 814914,
        objectCount: 10013,
        ratingType: 'Feature' as Rating
    },
    '10155484': {
        name: `Eighto Circles`,
        description: `Tried my best to fix this level's inconsistencies.`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 165900,
        likes: 12329,
        objectCount: 12701,
        ratingType: 'Feature' as Rating
    },
    '10238245': {
        name: `platforms of dusk`,
        description: `The update is here! I've wanted to update this level for the longest time. I hope you enjoy it! If you are stargrinding, avoid this level.`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 42163,
        likes: 2118,
        objectCount: 17379,
        ratingType: 'Feature' as Rating
    },
    '10966402': {
        name: `Popcorn`,
        description: `My Nc And Retro Level! RobTop Featured? Please? xD Thank For Play!`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 87644,
        likes: 5070,
        objectCount: 11926,
        ratingType: 'Feature' as Rating
    },
    '11335866': {
        name: `Drop Out `,
        description: `First 2.0 Circles! Hope you like! Visit my YT channel! `,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 69067,
        likes: 4591,
        objectCount: 12113,
        ratingType: 'Feature' as Rating
    },
    '11813101': {
        name: `astronaut circles`,
        description: `Hey Eric! I saw my level was soon on the list, so I encourage you to play the V2 I uploaded. It is more visually pleasing and better to play`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 64989,
        likes: 7552,
        objectCount: 8561,
        ratingType: 'Feature' as Rating
    },
    '11816658': {
        name: `Kirby Circle`,
        description: `:3`,
        difficulty: 'Harder',
        stars: 6,
        length: 'Long' as Length,
        downloads: 147988,
        likes: 10151,
        objectCount: 15378,
        ratingType: 'Feature' as Rating
    },
    '11918033': {
        name: `Friday Night`,
        description: `Updated to fix some stuff...still don't know why this terrible level was featured XD Pass is 1787`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 83538,
        likes: 5074,
        objectCount: 12000,
        ratingType: 'Feature' as Rating
    },
    '11951127': {
        name: `Entrance`,
        description: `new level " magnolia" pls rate for the featured :)!`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 16055,
        likes: 2544,
        objectCount: 15709,
        ratingType: 'Feature' as Rating
    },
    '11953778': {
        name: `Reality`,
        description: `Thanks for the support guys ;)`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 23512,
        likes: 2231,
        objectCount: 8320,
        ratingType: 'Feature' as Rating
    },
    '11958784': {
        name: `HeartBreaker`,
        description: `YES MMM OH GOD! My first nine circles level! Thanks for the feature rubrub :3`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 122159,
        likes: 14498,
        objectCount: 9059,
        ratingType: 'Feature' as Rating
    },
    '12239617': {
        name: `Xenogenesis`,
        description: `v23!? XD Finally, Xenogenesis was fixed.`,
        difficulty: 'Auto',
        stars: 1,
        length: 'Long' as Length,
        downloads: 581418,
        likes: 89460,
        objectCount: 11090,
        ratingType: 'Feature' as Rating
    },
    '12300295': {
        name: `If Jawbreaker Was L1`,
        description: `Reuploaded.. Follow me for more and check out My YouTube-channel too! c:`,
        difficulty: 'Normal',
        stars: 3,
        length: 'Long' as Length,
        downloads: 3232962,
        likes: 471904,
        objectCount: 9527,
        ratingType: 'Feature' as Rating
    },
    '12341888': {
        name: `If Sonic Wave was L1`,
        description: `Easy version of Sonic Wave by Cyclic. Enjoy the hardest lvl1 EVER`,
        difficulty: 'Insane',
        stars: 8,
        length: 'XL' as Length,
        downloads: 3779199,
        likes: 237362,
        objectCount: 20853,
        ratingType: 'Feature' as Rating
    },
    '12902542': {
        name: `Industrial Abyss`,
        description: `...`,
        difficulty: 'Hard',
        stars: 5,
        length: 'Long' as Length,
        downloads: 47292,
        likes: 4998,
        objectCount: 13479,
        ratingType: 'Feature' as Rating
    },
    '13073860': {
        name: `dubsteps`,
        description: `dubsteps circles `,
        difficulty: 'Hard',
        stars: 5,
        length: 'Long' as Length,
        downloads: 460069,
        likes: 68354,
        objectCount: 13412,
        ratingType: 'Feature' as Rating
    },
    '13433184': {
        name: `FAYRDUST`,
        description: `I hope they give is my class like nine circles`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 40200,
        likes: 5570,
        objectCount: 8203,
        ratingType: 'Feature' as Rating
    },
    '13524580': {
        name: `if infinite c was l1`,
        description: `A easy version of the demon called "Infinite Circles" Thanks for playing 8)`,
        difficulty: 'Normal',
        stars: 3,
        length: 'Long' as Length,
        downloads: 313660,
        likes: 53330,
        objectCount: 7594,
        ratingType: 'Feature' as Rating
    },
    '13699667': {
        name: `Mlg Swag Circles`,
        description: `I would like to apologise for this... I was 13, I am not proud of what I did...`,
        difficulty: 'Auto',
        stars: 1,
        length: 'Long' as Length,
        downloads: 750033,
        likes: 112827,
        objectCount: 33188,
        ratingType: 'Feature' as Rating
    },
    '13920616': {
        name: `Genesis`,
        description: ``,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 184717,
        likes: 18961,
        objectCount: 10001,
        ratingType: 'Feature' as Rating
    },
    '14160096': {
        name: `Future Circles`,
        description: `Updated to make it look better!`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 82257,
        likes: 8062,
        objectCount: 14124,
        ratingType: 'Feature' as Rating
    },
    '14374201': {
        name: `a mixed of colors `,
        description: `2000 likes!!`,
        difficulty: 'Harder',
        stars: 7,
        length: 'XL' as Length,
        downloads: 33186,
        likes: 2804,
        objectCount: 29981,
        ratingType: 'Feature' as Rating
    },
    '15798818': {
        name: `The Screamroom`,
        description: `Low detail mode is too hard to make, some moving parts are in high detail and are necessary. 261553 ;)`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 49615,
        likes: 4234,
        objectCount: 28969,
        ratingType: 'Feature' as Rating
    },
    '16723365': {
        name: `Altereffect`,
        description: `Auto key deleted. Verified by NucleusCore_34. OMG thanks RobTop`,
        difficulty: 'Hard',
        stars: 4,
        length: 'XL' as Length,
        downloads: 47777,
        likes: 5974,
        objectCount: 13370,
        ratingType: 'Feature' as Rating
    },
    '21900647': {
        name: `Machina`,
        description: `:P`,
        difficulty: 'Auto',
        stars: 1,
        length: 'Long' as Length,
        downloads: 431180,
        likes: 46358,
        objectCount: 12275,
        ratingType: 'Feature' as Rating
    },
    '53515815': {
        name: `Technological Meadow`,
        description: `I liked to do this level and also the music. I hope it is featured because it cost me a little to create this level. LiKe <3`,
        difficulty: 'Harder',
        stars: 6,
        length: 'Long' as Length,
        downloads: 15021,
        likes: 2539,
        objectCount: 33357,
        ratingType: 'Feature' as Rating
    },
    '61529537': {
        name: `Moonbeam`,
        description: `Inspired by Balengu Vortex and F3lixsram.`,
        difficulty: 'Harder',
        stars: 6,
        length: 'Long' as Length,
        downloads: 16695,
        likes: 1999,
        objectCount: 32064,
        ratingType: 'Feature' as Rating
    },
    '66077698': {
        name: `Hurbanovo`,
        description: `sequel na sturovo`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 7408,
        likes: 728,
        objectCount: 49694,
        ratingType: 'Feature' as Rating
    },
    '68944287': {
        name: `Holy balls a solO`,
        description: `balls (that's hi eric in latin)`,
        difficulty: 'Easy',
        stars: 2,
        length: 'Long' as Length,
        downloads: 85088,
        likes: 6869,
        objectCount: 66877,
        ratingType: 'Feature' as Rating
    },
    '71950911': {
        name: `Dimensional`,
        description: `inspired by nine circles, enjoy (for EVWNCP) :D`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 434017,
        likes: 34406,
        objectCount: 20365,
        ratingType: 'Feature' as Rating
    },
    '72258485': {
        name: `misty circles`,
        description: `yes, a nine circles styled level. i tried to keep as many elements from the original level as possible. for EVWNCP!`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 258304,
        likes: 32608,
        objectCount: 14631,
        ratingType: 'Feature' as Rating
    },
    '72383395': {
        name: `iPhone Redux`,
        description: `this level is not a redux and has nothing to do with iphones or apple (for EVWNCP) | <cr>good luck with the coin</c>`,
        difficulty: 'Easy',
        stars: 2,
        length: 'Long' as Length,
        downloads: 178601,
        likes: 13765,
        objectCount: 49193,
        ratingType: 'Feature' as Rating
    },
    '72423358': {
        name: `Crocles`,
        description: `croc circles. crocles. teehee.`,
        difficulty: 'Hard',
        stars: 4,
        length: 'Medium' as Length,
        downloads: 55384,
        likes: 7600,
        objectCount: 24801,
        ratingType: 'Feature' as Rating
    },
    '72498415': {
        name: `Joshua Vortex`,
        description: `Dedicated to every Josh out there. | Made for the EVWNCP! :)`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 326517,
        likes: 26144,
        objectCount: 58639,
        ratingType: 'Feature' as Rating
    },
    '72807796': {
        name: `Sadge`,
        description: `How it feels when an evw video ends. For evwncp.`,
        difficulty: 'Normal',
        stars: 3,
        length: 'Long' as Length,
        downloads: 38368,
        likes: 4173,
        objectCount: 39644,
        ratingType: 'Feature' as Rating
    },
    '72942759': {
        name: `PAHCles`,
        description: `pahc circles`,
        difficulty: 'Hard',
        stars: 5,
        length: 'Medium' as Length,
        downloads: 67721,
        likes: 8215,
        objectCount: 25455,
        ratingType: 'Feature' as Rating
    },
    '73240485': {
        name: `Valk`,
        description: `i like this level alot`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 8980,
        likes: 1235,
        objectCount: 49968,
        ratingType: 'Feature' as Rating
    },
    '73460770': {
        name: `AboR DebanK`,
        description: `Nc lvl for EVWCP! Made in 2 days! Im really proud of it. Next lvls will be longer i swear! Dedicated to EVW ofc! Rate 7-8*`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Medium' as Length,
        downloads: 469090,
        likes: 35628,
        objectCount: 21883,
        ratingType: 'Feature' as Rating
    },
    '74724111': {
        name: `Zen`,
        description: `scariest level in gd`,
        difficulty: 'Harder',
        stars: 6,
        length: 'Long' as Length,
        downloads: 12622,
        likes: 1836,
        objectCount: 28946,
        ratingType: 'Feature' as Rating
    },
    '75323912': {
        name: `Sparkscles`,
        description: `sparksomega circles`,
        difficulty: 'Harder',
        stars: 6,
        length: 'Long' as Length,
        downloads: 38235,
        likes: 3960,
        objectCount: 16975,
        ratingType: 'Feature' as Rating
    },
    '75361742': {
        name: `Star rain`,
        description: ``,
        difficulty: 'Harder',
        stars: 6,
        length: 'Long' as Length,
        downloads: 6616,
        likes: 612,
        objectCount: 42015,
        ratingType: 'Feature' as Rating
    },
    '75731172': {
        name: `Triple A`,
        description: `For Evw, AAAAAlex, and Renn241. Update by BowtieGD.`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 21925,
        likes: 1705,
        objectCount: 32970,
        ratingType: 'Feature' as Rating
    },
    '77695213': {
        name: `Zaana`,
        description: `scariest level in gd (PART 2 O_O)`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 34063,
        likes: 3711,
        objectCount: 27088,
        ratingType: 'Feature' as Rating
    },
    '78446820': {
        name: `Umbra Lev Iathan`,
        description: `reupload and redeco of umbra circles `,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 260654,
        likes: 28913,
        objectCount: 27348,
        ratingType: 'Feature' as Rating
    },
    '78743399': {
        name: `Generic wave iii`,
        description: `Special thanks to ShadowIan for giving me permission to make an official sequel to GWII.`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 57787,
        likes: 4416,
        objectCount: 55632,
        ratingType: 'Feature' as Rating
    },
    '78936509': {
        name: `6534`,
        description: `My modern NC level!! NC inspired by AlasstorGD. had alot of fun with this one! Enjoy :D`,
        difficulty: 'Harder',
        stars: 6,
        length: 'Medium' as Length,
        downloads: 14517,
        likes: 1350,
        objectCount: 31421,
        ratingType: 'Feature' as Rating
    },
    '79188336': {
        name: `Nine Circles`,
        description: `Easy`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 162186,
        likes: 11512,
        objectCount: 35408,
        ratingType: 'Feature' as Rating
    },
    '80725458': {
        name: `Dubby wave`,
        description: `Made for my friend Dubbyball as a birthday gift!  2.2 Update! Should be balanced and optimized better!`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 8197,
        likes: 828,
        objectCount: 37747,
        ratingType: 'Feature' as Rating
    },
    '82980620': {
        name: `Whats Good`,
        description: `Made in a year`,
        difficulty: 'Normal',
        stars: 3,
        length: 'Long' as Length,
        downloads: 118049,
        likes: 8505,
        objectCount: 19185,
        ratingType: 'Feature' as Rating
    },
    '84155605': {
        name: `Groovy Circles`,
        description: `This level took 5 months to build, but I finally finished it. An idea by Brumik turned into a full level. Dedicated to ReYzen Group 8)`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 12878,
        likes: 1128,
        objectCount: 115295,
        ratingType: 'Feature' as Rating
    },
    '85853040': {
        name: `Infinity BASICIRCLES`,
        description: `Back to the 1.9 STYLE ;) (1.9 + Glow = 2.?) Inspired By DoraBae & Nine Circles (For EVWNCP ~) :D`,
        difficulty: 'Harder',
        stars: 7,
        length: 'Long' as Length,
        downloads: 25933,
        likes: 2732,
        objectCount: 24742,
        ratingType: 'Feature' as Rating
    },
    '85979871': {
        name: `Spectral Nebula`,
        description: `*Uploaded with permission from Jordi* - Special thanks to Rifct for helping me add touches :)`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 22415,
        likes: 2203,
        objectCount: 40111,
        ratingType: 'Feature' as Rating
    },
    '88051670': {
        name: `Downward Spiral`,
        description: ` [A T R O C I T Y E X H I B I T I O N] playtested by ELLVO and Ricft.  `,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 17940,
        likes: 1377,
        objectCount: 11670,
        ratingType: 'Feature' as Rating
    },
    '93375725': {
        name: `Chapter of Time`,
        description: `New level, enjoy it! :)`,
        difficulty: 'Hard',
        stars: 5,
        length: 'Long' as Length,
        downloads: 22859,
        likes: 2764,
        objectCount: 22608,
        ratingType: 'Feature' as Rating
    },
    '95109514': {
        name: `Western VorteX`,
        description: `last 2.1 level (hopefully)`,
        difficulty: 'Insane',
        stars: 9,
        length: 'Long' as Length,
        downloads: 7962,
        likes: 975,
        objectCount: 32363,
        ratingType: 'Feature' as Rating
    },
    '103370684': {
        name: `messiers Twin B`,
        description: `Sequel?? Remake?? I dont know what to call it. 3 days of work, honestly had fun for once.`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Medium' as Length,
        downloads: 6771,
        likes: 515,
        objectCount: 49692,
        ratingType: 'Feature' as Rating
    },
    '106040563': {
        name: `absolute NINE CIRCLE`,
        description: `Dedicace a Paizo et FarawGD`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 89079,
        likes: 8109,
        objectCount: 17335,
        ratingType: 'Feature' as Rating
    },
    '106237782': {
        name: `absolute JAWBREAKER`,
        description: `Sequel to absolute NINE CIRCLE`,
        difficulty: 'Insane',
        stars: 8,
        length: 'Long' as Length,
        downloads: 362901,
        likes: 34383,
        objectCount: 40096,
        ratingType: 'Feature' as Rating
    },
}

export { downloadedAPIInfo }