name: Update Fake API Information
on:
  schedule:
  - cron: "0 0 * * 1,3,5"
  workflow_dispatch:

jobs:
  update_info:
    name: Update API Information
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
             ls ${{ github.workspace }}
      - name: install python
        run: sudo add-apt-repository ppa:deadsnakes/ppa
      - run: sudo apt-get install -y python3.12
      - name: run scrape api file
        run: python3 scrape_api.py
      - name: commit and push changes
        run: git add .
      - run: git commit -am "Automatically update fake API information"
      - run: git push
