name: Update Fake API Information
on:
  schedule:
  - cron: "0 0 * * 4"
  workflow_dispatch:

jobs:
  clone:
    name: clone repository
    runs-on: ubuntu-22.04
    steps:
      - run: git clone https://github.com/redstone59/Nine-Circ-le
  python:
    name: install python
    runs-on: ubuntu-22.04
    needs: [clone]
    steps:
      - run: sudo add-apt-repository ppa:deadsnakes/ppa
      - run: sudo apt-get install -y python3.12
  scrape_api:
    name: run scrape api file
    runs-on: ubuntu-22.04
    needs: [python]
    steps:
      - run: |
          ls ${{ github.workspace }}
      - run: python scrape_api.py
  push:
    name: commit and push changes
    runs-on: ubuntu-22.04
    needs: [scrape_api]
    steps:
      - run: git add .
      - run: git commit -am "Automatically update fake API information"
      - run: git push
